### ISSUE TITLE
Error: spawn ns ENOENT

### ISSUE THREAD

**Issue by ReneMueller4P** [NativeScript/nx#14]
Hi, I have a problem when compiling applications I get the following error. on my Windows 10 machine. 
```
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn ns ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ns',
  path: 'ns',
  spawnargs: [ 'clean' ]
```
Is there any solution to this ?

**Comment by mahmoudajawad** [comment]
I had similar issue the first time I tried this package out, turned out to be some issue with my node installation, where I needed to clean-install node, npm again.

**Comment by ReneMueller4P** [comment]
Unfortunately the reinstallation of node and npm did not help. Are there any other ideas to solve the problem

**Comment by mahmoudajawad** [comment]
Maybe you are hitting similar versions issues like I did with #13 ?

**Comment by NathanWalker** [comment]
This seems relevant:
https://stackoverflow.com/questions/43230346/error-spawn-npm-enoent

@ReneMueller4P try this when you can, in your project root and if using VS Code, you can open the builder like this:
```
code node_modules/@nativescript/nx/src/builders/build/builder.js
```
If not using VS Code, you can manually open that file in your editor. If using 0.0.4 latest of @nativescript/nx on line 92, you can try some of the options mentioned in the stack overflow post. I don't have a windows machine here to test with but lemme know if you find a combo that helps Windows and we can make an adjustment.

**Comment by govi2010** [comment]
@NathanWalker 
yes we need to use `ns.cmd` in windows. 

I have create PR for to fix this.
https://github.com/NativeScript/nx/pull/16

**Comment by ReneMueller4P** [comment]
Soory for the late answer, I come only tomorrow to test nx in the company, but apparently it has already made  @govi2010 . Will also still test it tomorrow.

**Comment by govi2010** [comment]
This PR should solve this error.

Currently I modified file in my node_module.

**Comment by fpaaske** [comment]
I still get this issue on a brand new setup, calling the app nx-test and using angular for ui;

```
npx create-nx-workspace@latest --cli=nx --preset=empty
cd nx-test
npm install --save-dev @nativescript/nx
npx nx g @nativescript/nx:app hello-world
```
Then try to run it:
```
➜  nx-test git:(master) ✗ npx nx run nativescript-hello-world:ios --verbose

> nx run nativescript-hello-world:ios --verbose
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn ns ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn ns',
  path: 'ns',
  spawnargs: [ 'debug', 'ios', '--force' ]
}

———————————————————————————————————————————————

>  NX   ERROR  Running target "nativescript-hello-world:ios" failed

  Failed tasks:

  - nativescript-hello-world:ios

  Hint: run the command with --verbose for more details.
```

I was already running this command with `--verbose`. Any tips?

**Comment by marckassay** [comment]
@fpaaske I too used `nvm`, switched `node` version and forgot that `nativescript` needs to be installed.

I suggest, and for anyone else with that error, that `ns package-manager get` needs to be executed to ensure that you're using the desired node package manager. Initially, I was using yarn and decided to use npm between switching node versions. Yarn also needs to be installed when switching node versions. And if you're using yarn, don't forget to opt-in (or install) for corepack. See [here](https://yarnpkg.com/getting-started/install#install-corepack) for info on that.
